import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase configuration for the Luxuriskin Aesthetic Clinic project.
///
/// This was hand-written from the Firebase web app config rather than
/// generated by the FlutterFire CLI, so only the web target is wired up.
/// To run this app on Android/iOS/macOS, install the FlutterFire CLI and run
/// `flutterfire configure` — it will fetch the platform-specific keys
/// (google-services.json / GoogleService-Info.plist) and rewrite this file
/// with a `DefaultFirebaseOptions` for each platform.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions has not been configured for '
          '$defaultTargetPlatform. Run `flutterfire configure` to add it.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX973e_YzX4sF4_LutnZw30VuLxoMAKV8',
    appId: '1:185458071561:web:c9698ea0c04f5a367040d8',
    messagingSenderId: '185458071561',
    projectId: 'luxuriskin-aesthetic-clinic',
    authDomain: 'luxuriskin-aesthetic-clinic.firebaseapp.com',
    storageBucket: 'luxuriskin-aesthetic-clinic.firebasestorage.app',
    measurementId: 'G-CGE8C33N0V',
  );
}
